title: Maxwell Benman
description: Maxwell Benman is a web, UX, and graphic designer in Boston, MA. He likes to
  team up with people to create nifty things that make people smile, and
  wants to join a fast-paced, mission-driven team that values great work
  in all aspects.

environment: development

baseurl: ""
url: ""


collections:
  - projects
  - image_gallery


defaults:
  -
    scope:
      path: "assets/img"
    values:
      image: true
  -
    scope:
      path: "assets/siteContent"
    values:
      siteContent: true        
  -
    scope:
      path: "assets/img/sign_shop"
    values:
      proj: "sign_shop"
  -
    scope:
      path: "assets/img/protectThePack"
    values:
      proj: "protectThePack"
  -
    scope:
      path: "assets/img/betterWeather"
    values:
      proj: "betterWeather"
  -
    scope:
      path: "assets/img/NUPR"
    values:
        proj: "NUPR"
  -
    scope:
      path: "assets/img/resume"
    values:
        proj: "resume"
  -
    scope:
      path: "assets/img/smartEnergy"
    values:
        proj: "smartEnergy"
  -
    scope:
      path: "assets/img/thisWebsite"
    values:
        proj: "thisWebsite"


theme: jekyll-theme-minimal