title: Maxwell Benman
description: Maxwell Benman is a web, UX, and graphic designer in Boston, MA. He likes to
  team up with people to create nifty things that make people smile, and
  wants to join a fast-paced, mission-driven team that values great work
  in all aspects.

environment: development

baseurl: ""
url: ""


collections:
  - projects
  - image_gallery
  - about


defaults:
  -
    scope:
      path: "assets/images"
    values:
      image: true
  -
    scope:
      path: "assets/images/siteContent"
    values:
      siteContent: true        
  -
    scope:
      path: "assets/images/media/sign_shop"
    values:
      proj: "signShop"
  -
    scope:
      path: "assets/images/media/protectThePack"
    values:
      proj: "protectThePack"
  -
    scope:
      path: "assets/images/media/betterWeather"
    values:
      proj: "betterWeather"
  -
    scope:
      path: "assets/images/media/NUPR"
    values:
        proj: "NUPR"
  -
    scope:
      path: "assets/images/media/resume"
    values:
      proj: "resume"
  -
    scope:
      path: "assets/images/media/smartEnergy"
    values:
      proj: "smartEnergy"
  -
    scope:
      path: "assets/images/media/thisWebsite"
    values:
      proj: "thisWebsite"


theme: jekyll-theme-minimal