title: Maxwell Benman
description: Maxwell Benman is a web, UX, and graphic designer in Boston, MA. He likes to
  team up with people to create nifty things that make people smile, and
  wants to join a fast-paced, mission-driven team that values great work
  in all aspects.


theme: jekyll-theme-minimal